openapi: 3.0.0
info:
  title: attendance_management
  version: 1.0.0
servers:
  - url: http://localhost:8080
tags:
  - name: employees
  - name: companies
  - name: employments
  - name: positions
  - name: salary_types
  - name: attendance
paths:
  /employees:
    post:
      tags:
        - employees
      summary: create_employee
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: aaa
                phone_number: '111'
                email: aaa@example.com
                employee_number: 1
                password: securePassword123
                password_confirm: securePassword123
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - employees
      summary: get_all_employees
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employees/1003:
    put:
      tags:
        - employees
      summary: update_employees
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: 山田 皇帝
                phone_number: 090-8888-0000
                email: yamada.koutei@example.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employees/1:
    delete:
      tags:
        - employees
      summary: delete_employee
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /company:
    post:
      tags:
        - companies
      summary: create_company
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: moka-company
                company_number: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - companies
      summary: get_company_info
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - companies
      summary: update_employee
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: moka-chan-company
                company_number: 1
      parameters:
        - name: ''
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - companies
      summary: delete_company
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /employment:
    post:
      tags:
        - employments
      summary: create_employment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                employee_id: 1
                company_id: 1
                position_id: 1
                start_date: '2023-08-06T12:34:56Z'
                end_date: '2023-12-31T23:59:59Z'
                salary_type_id: 1
                employment_number: 987654321
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - employments
      summary: get_employment
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '987654321'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - employments
      summary: update_employment
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                employee_id: 1
                company_id: 1
                position_id: 1
                start_date: '2023-08-06T12:34:56Z'
                end_date: '2024-12-31T23:59:59Z'
                salary_type_id: 1
                employment_number: 987654321
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - employments
      summary: delete_employment
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '987654321'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /position:
    post:
      tags:
        - positions
      summary: create_position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: monthly_salary
                position_number: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - positions
      summary: get_position_info
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - positions
      summary: update_position
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: monthly_salary
                position_number: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - positions
      summary: New Request
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /salary_type:
    post:
      tags:
        - salary_types
      summary: create_salary_type
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: monthly_salary
                salary_type_number: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - salary_types
      summary: get_salary_type
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - salary_types
      summary: New Request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                type: hourly_salary
                salary_type_number: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - salary_types
      summary: New Request
      parameters:
        - name: number
          in: query
          schema:
            type: integer
          example: '0'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /attendances/check-in/1:
    post:
      tags:
        - attendance
      summary: check-in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                employment_id: 3
                check_in_time: '2023-10-12T08:00:00Z'
                attendance_number: 1
                latitude: 35.6895
                longitude: 139.6917
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /attendances/check-out/1:
    put:
      tags:
        - attendance
      summary: check-out
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                check_out_time: '2023-10-16T17:34:56Z'
                latitude: 35.6895
                longitude: 139.6917
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /attendances:
    get:
      tags:
        - attendance
      summary: get_attendance
      parameters:
        - name: attendance_number
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /attendances/all:
    get:
      tags:
        - attendance
      summary: get_all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /attendances/1:
    put:
      tags:
        - attendance
      summary: update_attendance
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                employee_number: 1
                employment_id: 3
                check_in_time: '2023-10-12T08:00:00Z'
                check_out_time: '2023-10-16T06:46:41.664Z'
                attendance_number: 1
                latitude: 35.6895
                longitude: 139.6917
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - attendance
      summary: New Request
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
